[build]
  publish = "public"
  command = "echo 'No build step needed'"

[build.environment]
  NODE_VERSION = "18"

[dev]
  port = 8888
  edge_functions = "netlify/edge-functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/style.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/app.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Route API calls to edge function
[[edge_functions]]
  path = "/api/*"
  function = "api"